title: "MRU English Honours Conference Fall 2024"
subtitle: "Romance & Community" # [NEED CONFIRMATION: Is this the official subtitle?]
date: "December 6th, 2024"
time: "10:00 AM - 3:30 PM"
venue:
  name: "The Knuckle"
  room: "3001"
  building: "EA Building"
  floor: "3rd"
  address: "4825 Mt Royal Gate SW, Calgary, AB T3E 6K6" # [NEED CONFIRMATION: Is this the correct address?]
description: |
  Often when people hear "Romance," they think of passionate love stories or steamy novel covers. By using the concept of "Romance" and exploring its role in literature, relationships, and societal change, this conference will engage in the intersection of community and romance. In literary studies, the concept of Romance goes beyond the popular understanding—referring to a deep appreciation for beauty, emotion, and idealism encompassing and extending interpersonal relationships. The broader understanding of Romance includes a passionate engagement with art, nature, ideas, and the human experience. Our conference will reconstruct understanding of romance—emphasizing the power to inspire adventure, foster idealism, and even save the world. We will engage the communal aspects of romance and its impact on pedagogy and criticism, and how it will revitalize the study of literature and language. Together, we'll explore how compassion for humanity and beauty can reshape our academic and personal landscapes.
quotes:
  - text: "LIBERAL ARTS ARE THE ARTS THAT LIBERATE!"
    author: null
  - text: "My friends, love is better than anger. Hope is better than fear. Optimism is better than despair. So let us be loving, hopeful and optimistic. And we'll change the world."
    author: "Jack Layton"
  - text: "Dialogue cannot exist, however, in the absence of a profound love for the world and for people … Love is at the same time the foundation of dialogue and dialogue itself."
    author: "Paulo Freire"
    source: "Pedagogy of the Oppressed"